/*
Copyright 2013 Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
Distributed under the BSD-3 license. See the file LICENSE for details.
*/

package gov.sandia.n2a;

public class VersionConstants {

    // All of these numbers are changed when you execute
    // the Ant build script.  You change these numbers
    // by changing the numbers in the Ant build script
    // before you execute it.

    // ** DO NOT EDIT THIS FILE **

    public static final String MAJOR = "0";
    public static final String MINOR = "9";
    public static final String SERVICE = "0";
    public static final String BUILD = "b20130528-0824";
}
