/*
Copyright 2013 Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
Distributed under the BSD-3 license. See the file LICENSE for details.
*/

/* Generated By:JJTree: Do not edit this line. ASTConstant.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,
 * NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */

package gov.sandia.n2a.language.parse;

import gov.sandia.n2a.language.functions.EvaluationContext;
import gov.sandia.n2a.language.functions.EvaluationException;

public class ASTConstant extends ASTNodeBase {


    ////////////////////
    // AUTO-GENERATED //
    ////////////////////

    public ASTConstant(Object value) {
        super(value, ExpressionParserTreeConstants.JJTCONSTANT);
    }

    public ASTConstant(int id) {
        super(id);
    }

    public ASTConstant(ExpressionParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) throws ParseException {
        return visitor.visit(this, data);
    }


    ////////////
    // CUSTOM //
    ////////////

    @Override
    public String toString() {
        return getValue().toString();
    }

    @Override
    public String render(ASTRenderingContext context)
    {
        // Long & Short rendering
        Object value = getValue ();
        if(value instanceof String) {
            return "\"" + value.toString() + "\"";
        }
        return value.toString();
    }


    ////////////////
    // EVALUATION //
    ////////////////

    // Currently will evaluate to a String or Double object
    // as those are the only constants we recognize in parsing.
    @Override
    public Object eval(EvaluationContext context) throws EvaluationException {
        return getValue();
    }
}
/* JavaCC - OriginalChecksum=8707db8971df053468c80f231e54ed75 (do not edit this line) */
