/*
Copyright 2013 Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
Distributed under the BSD-3 license. See the file LICENSE for details.
*/

/* Generated By:JJTree: Do not edit this line. ASTListNode.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,
 * NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */

package gov.sandia.n2a.language.parse;

import gov.sandia.n2a.language.EvaluationContext;
import gov.sandia.n2a.language.EvaluationException;
import gov.sandia.n2a.language.Type;

public class ASTListNode extends ASTNodeBase {


    ////////////////////
    // AUTO-GENERATED //
    ////////////////////

    public ASTListNode(Object value) {
        super(value, ExpressionParserTreeConstants.JJTLISTNODE);
    }

    public ASTListNode(int id) {
        super(id);
    }

    public ASTListNode(ExpressionParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) throws ParseException {
        return visitor.visit(this, data);
    }


    ////////////
    // CUSTOM //
    ////////////

    @Override
    public String toString() {
        return getValue().toString();
    }

    @Override
    public String render(ASTRenderingContext context)
    {
        // Long & Short rendering
        String ret = "";
        for(int a = 0; a < getCount(); a++) {
            ret += context.render (getChild (a));
            if(a != getCount() - 1) {
                ret += ", ";
            }
        }
        return ret;
    }


    ////////////////
    // EVALUATION //
    ////////////////

    @Override
    public Type eval (EvaluationContext context) throws EvaluationException
    {
        throw new EvaluationException ("List is not a formal N2A Type.");
    }
}
/* JavaCC - OriginalChecksum=d551700b54e6299c518a2537b8744651 (do not edit this line) */
