/*
Copyright 2013 Sandia Corporation.
Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
the U.S. Government retains certain rights in this software.
Distributed under the BSD-3 license. See the file LICENSE for details.
*/

/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,
 * NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */

package gov.sandia.n2a.language.parse;

import gov.sandia.n2a.language.EvaluationContext;
import gov.sandia.n2a.language.EvaluationException;
import gov.sandia.n2a.language.Type;


// Unnecessary class used simply to encapsulate the entire
// tree during the parsing process.

public class ASTStart extends ASTNodeBase {


    ////////////////////
    // AUTO-GENERATED //
    ////////////////////

    public ASTStart(int id) {
        super(id);
    }

    public ASTStart(ExpressionParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) throws ParseException {
        return visitor.visit(this, data);
    }


    ////////////
    // CUSTOM //
    ////////////

    @Override
    public String toString() {
        return "START";
    }

    @Override
    public String render(ASTRenderingContext context)
    {
        // Long & Short rendering
        return toString();
    }


    ////////////////
    // EVALUATION //
    ////////////////

    @Override
    public Type eval (EvaluationContext context) throws EvaluationException
    {
        return getChild (0).eval (context);
    }
}
/* JavaCC - OriginalChecksum=a98231396689e1184618f64cb7d1e176 (do not edit this line) */
