/* Generated By:JavaCC: Do not edit this line. ExpressionParserDefaultVisitor.java Version 6.0_1 */
package gov.sandia.n2a.language.parse;

public class ExpressionParserDefaultVisitor implements ExpressionParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data) throws ParseException{
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data) throws ParseException{
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data) throws ParseException{
    return defaultVisit(node, data);
  }
  public Object visit(ASTOpNode node, Object data) throws ParseException{
    return defaultVisit(node, data);
  }
  public Object visit(ASTListNode node, Object data) throws ParseException{
    return defaultVisit(node, data);
  }
  public Object visit(ASTUnitNode node, Object data) throws ParseException{
    return defaultVisit(node, data);
  }
  public Object visit(ASTMatrixNode node, Object data) throws ParseException{
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarNode node, Object data) throws ParseException{
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunNode node, Object data) throws ParseException{
    return defaultVisit(node, data);
  }
  public Object visit(ASTConstant node, Object data) throws ParseException{
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=7304c0752be30565e363a05b42355efe (do not edit this line) */
