/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 6.0_1 */
package gov.sandia.n2a.language.parse;

public interface ExpressionParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOPNODE = 2;
  public int JJTLISTNODE = 3;
  public int JJTUNITNODE = 4;
  public int JJTMATRIXNODE = 5;
  public int JJTVARNODE = 6;
  public int JJTCONSTANT = 7;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "OpNode",
    "ListNode",
    "UnitNode",
    "MatrixNode",
    "VarNode",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=6761bc502cf13ebf3d6b87be402f0f2d (do not edit this line) */
