/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 5.0 */
package gov.sandia.n2a.language.parse;

public interface ExpressionParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOPNODE = 2;
  public int JJTLISTNODE = 3;
  public int JJTUNITNODE = 4;
  public int JJTMATRIXNODE = 5;
  public int JJTVARNODE = 6;
  public int JJTFUNNODE = 7;
  public int JJTCONSTANT = 8;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "OpNode",
    "ListNode",
    "UnitNode",
    "MatrixNode",
    "VarNode",
    "FunNode",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=2e4d4cfcc4561b9fc0fc93b58d806eca (do not edit this line) */
